# Generated by Django 5.0.1 on 2025-09-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
    ]
