# Generated by Django 5.2.5 on 2025-09-03 17:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(help_text='Número único de licencia médica', max_length=50, unique=True, verbose_name='Número de Licencia')),
                ('specialization', models.CharField(help_text='Especialidad médica del doctor', max_length=100, verbose_name='Especialización')),
                ('experience_years', models.PositiveIntegerField(help_text='Años de experiencia profesional', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Años de Experiencia')),
                ('consultation_fee', models.DecimalField(decimal_places=2, help_text='Costo de la consulta médica', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tarifa de Consulta')),
                ('bio', models.TextField(help_text='Información adicional sobre el doctor', verbose_name='Biografía')),
                ('is_available', models.BooleanField(default=True, help_text='Indica si el doctor está disponible para citas', verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
